GapClipFile
START CMD
START SKID MANUAL
START SKID AUTO
MW CNTRL ENABLE/DISABLE
MANUAL STI RESET CMD
SPARE 26 CMD
VOLTAGE RAISE CMD
RESET CMD
XN25 REF RAISE CMD
PRINT LOG CMD
OP_INTRFC
XN25RSE
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.N25RSE_MX.B_MUX_N_1
DATA_IO.RL2.BW_V_25
DATA_IO.LL2.BW_V_25
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
VRSE_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC.RSEVLTS_MB.B_NAME
DATA_IO.LL2.BW_V_25
DATA_IO.RL2.BW_V_25
OP_INTRFC.RSEVLTS_H.B_NAME
OP_INTRFC
VOLT_RSE
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.VRSE_MX.B_MUX_N_1
OP_INTRFC
STR_SKDMAN
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.STRMAN_MX.B_MUX_N_1
OP_INTRFC
STR_SKDAUT
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.STRAUTO_MX.B_MUX_N_1
DATA_IO.RL2.BW_V_30
DATA_IO.LL2.BW_V_30
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
STRMAN_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC.SSMAN_H.B_NAME
DATA_IO.LL2.BW_V_30
DATA_IO.RL2.BW_V_30
OP_INTRFC.SSMAN_MB.B_NAME
DATA_IO.RL2.BW_V_29
DATA_IO.LL2.BW_V_29
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
STRAUTO_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC.SSAUT_H.B_NAME
DATA_IO.LL2.BW_V_29
DATA_IO.RL2.BW_V_29
OP_INTRFC.SSAUT_MB.B_NAME
DATA_IO.RL2.BW_V
DATA_IO.LL2.BW_V
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
START_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
DATA_IO.LL2.BW_V
DATA_IO.RL2.BW_V
OP_INTRFC.DCS_STRTOR.OR
OP_INTRFC
START
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.START_MX.B_MUX_N_1
DATA_IO.DCS.BW_V_30
OP_INTRFC
SSMAN_MB
DESC = START SKID MANUAL SELECT
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_30
OP_INTRFC
SSMAN_H
DESC = START SKID MANUAL SELECT
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_29
OP_INTRFC
SSAUT_MB
DESC = START SKID AUTO SELECT
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_29
OP_INTRFC
SSAUT_H
DESC = START SKID AUTO SELECT
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC
SP_83_H
DESC = RELEASE STI COMMAND
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.RL2.BW_V_25
DATA_IO.LL2.BW_V_25
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
SPR26_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC.SPARE_E.B_NAME
DATA_IO.LL2.BW_V_25
DATA_IO.RL2.BW_V_25
OP_INTRFC.SPARE_MB.B_NAME
DATA_IO.DCS.BW_V_26
OP_INTRFC
SPARE_MB
DESC = SPARE
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_26
OP_INTRFC
SPARE_E
DESC = SPARE
UNITS = LOCAL MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC
SPARE_26
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.SPR26_MX.B_MUX_N_1
DATA_IO.DCS.BW_V_27
OP_INTRFC
SI_RELSEMB
DESC = RELEASE STI COMMAND
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_27
OP_INTRFC
RSEVLTS_MB
DESC = MODBUS VOLTAGE RAISE
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_25
OP_INTRFC
RSEVLTS_H
DESC = HARDWARE VOLTAGE RAISE
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_25
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
RESET_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
HMI_BO.BW_24_113L.OR
OP_INTRFC.BW_24_113R.OR
OP_INTRFC.RESET_MB.B_NAME
DATA_IO.DCS.BW_V_24
OP_INTRFC
RESET_MB
DESC = MODBUS RESET
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_24
OP_INTRFC
RESET
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.RESET_MX.B_MUX_N_1
OP_INTRFC
PRINT_LOG
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.PLOG_MX.B_MUX_N_1
DATA_IO.RL2.BW_V_22
DATA_IO.LL2.BW_V_22
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
PLOG_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
LOC_REM.PRTLOG_H.B_NAME
DATA_IO.LL2.BW_V_22
DATA_IO.RL2.BW_V_22
LOC_REM.PRTLOG_.B_NAME
DATA_IO.RL2.BW_V_23
DATA_IO.LL2.BW_V_23
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
N25RSE_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
LOC_REM.R_N25R_H.B_NAME
DATA_IO.LL2.BW_V_23
DATA_IO.RL2.BW_V_23
LOC_REM.R_N25R_MB.B_NAME
DATA_IO.DCS.BW_V_28
OP_INTRFC
MW_ENBL_MB
DESC = MW CONTROL ENABLE
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_28
DATA_IO.RL2.BW_V_28
DATA_IO.LL2.BW_V_28
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
MWENDS_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
DATA_IO.LL2.BW_V_28
DATA_IO.RL2.BW_V_28
OP_INTRFC.MW_ENBL_MB.B_NAME
OP_INTRFC
MAN_ENDSBL
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.MWENDS_MX.B_MUX_N_1
OP_INTRFC
MANSTI_RST
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
OP_INTRFC.MANSTIR_MX.B_MUX_N_1
DATA_IO.RL2.BW_V_27
DATA_IO.LL2.BW_V_27
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC
MANSTIR_MX
FONTINDEX = 16
POSINDEX = 1
SHOW_U = 1, SHOW_GRP_USG = 0
CNTRL_MODE.SELECT.I_NAME
OP_INTRFC.SP_83_H.B_NAME
DATA_IO.LL2.BW_V_27
DATA_IO.RL2.BW_V_27
OP_INTRFC.SI_RELSEMB.B_NAME
OP_INTRFC
DCS_STRTOR
FONTINDEX = 0
POSINDEX = 4
SHOW_U = 1, SHOW_GRP_USG = 0
LOC_REM.START_MB.B_NAME
LOC_REM.START_RH.B_NAME
DATA_IO.RL2.BW_V_113
DATA_IO.RL2.BW_V_24
OP_INTRFC
BW_24_113R
FONTINDEX = 0
POSINDEX = 0
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.RL2.BW_V_24
DATA_IO.RL2.BW_V_113
N3N40_BI.REM_START.BI_L
LOC_REM
START_RH
DESC = REMOTE START
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
N3N40_BI.REM_START.BI_L
DATA_IO.DCS.BW_V
LOC_REM
START_MB
DESC = MODBUS START
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V
N3N41_BI.LOC_START.BI_L
LOC_REM
START_H
DESC = HARDWARE START
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
N3N41_BI.LOC_START.BI_L
DATA_IO.DCS.BW_V_23
LOC_REM
R_N25R_MB
DESC = MAINTENCE RAISE N25
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_23
LOC_REM
R_N25R_H
DESC = MAINTENCE RAISE N25
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
LOC_REM
PRTLOG_H
DESC = HARDWARE PRINT DATA LOG
UNITS = HARDWARE
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_22
LOC_REM
PRTLOG_
DESC = MODBUS PRINT DATA LOG
UNITS = REMOTE MB
GROUP = MODBUS INPUTS
USAGE = 1
FONTINDEX = 0
POSINDEX = 3
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.DCS.BW_V_22
DATA_IO.LL2.BW_V_113
DATA_IO.LL2.BW_V_24
HMI_BO
BW_24_113L
FONTINDEX = 0
POSINDEX = 0
SHOW_U = 1, SHOW_GRP_USG = 0
DATA_IO.LL2.BW_V_24
DATA_IO.LL2.BW_V_113




/////////////

