
DATA_IO_DCS_BW_V_82;
DATA_IO_RL2_BW_V_82;
DATA_IO_LL2_BW_V_82;
CNTRL_MODE_SELECT_I_NAME;
OP_INTRFC_STGEN_MX;
DATA_IO_DCS_BW_V_91;
DATA_IO_RL2_BW_V_91;
DATA_IO_LL2_BW_V_91;
STG9_MX;
DATA_IO_DCS_BW_V_90;
DATA_IO_RL2_BW_V_90;
DATA_IO_LL2_BW_V_90;
STG8_MX;
DATA_IO_DCS_BW_V_89;
DATA_IO_RL2_BW_V_89;
DATA_IO_LL2_BW_V_89;
STG7_MX;
DATA_IO_DCS_BW_V_88;
DATA_IO_RL2_BW_V_88;
DATA_IO_LL2_BW_V_88;
STG6_MX;
DATA_IO_DCS_BW_V_87;
DATA_IO_RL2_BW_V_87;
DATA_IO_LL2_BW_V_87;
STG5_MX;
DATA_IO_DCS_BW_V_86;
DATA_IO_RL2_BW_V_86;
DATA_IO_LL2_BW_V_86;
STG4_MX;
DATA_IO_DCS_BW_V_85;
DATA_IO_RL2_BW_V_85;
DATA_IO_LL2_BW_V_85;
STG3_MX;
DATA_IO_DCS_BW_V_84;
DATA_IO_RL2_BW_V_84;
DATA_IO_LL2_BW_V_84;
STG2_MX;
DATA_IO_DCS_BW_V_83;
DATA_IO_RL2_BW_V_83;
DATA_IO_LL2_BW_V_83;
STG1_MX;
DATA_IO_DCS_BW_V_93;
DATA_IO_RL2_BW_V_93;
DATA_IO_LL2_BW_V_93;
STG11_MX;
DATA_IO_DCS_BW_V_92;
DATA_IO_RL2_BW_V_92;
DATA_IO_LL2_BW_V_92;
STG10_MX;
OP_INTRFC_MAN_STG_EN;
OP_INTRFC_STGEN_MX;
OP_INTRFC_MAN_STG_11;
OP_INTRFC_STG11_MX;
OP_INTRFC_MAN_STG_10;
OP_INTRFC_STG10_MX;
OP_INTRFC_MAN_STG_09;
OP_INTRFC_STG9_MX;
OP_INTRFC_MAN_STG_08;
OP_INTRFC_STG8_MX;
OP_INTRFC_MAN_STG_07;
OP_INTRFC_STG7_MX;
OP_INTRFC_MAN_STG_06;
OP_INTRFC_STG6_MX;
OP_INTRFC_MAN_STG_05;
OP_INTRFC_STG5_MX;
OP_INTRFC_MAN_STG_04;
OP_INTRFC_STG4_MX;
OP_INTRFC_MAN_STG_03;
OP_INTRFC_STG3_MX;
OP_INTRFC_MAN_STG_02;
OP_INTRFC_STG2_MX;
OP_INTRFC_MAN_STG_01;
OP_INTRFC_STG1_MX;


//// MANUAL STAGE VALVE ENABLE BLOQUE 1

  switch (CNTRL_MODE_SELECT_I_NAME){
    
    case 2:
      OP_INTRFC_STGEN_MX = DATA_IO_LL2_BW_V_82;
    break;
    case 3:
      OP_INTRFC_STGEN_MX = DATA_IO_RL2_BW_V_82;
    break;    
    case 5:
      OP_INTRFC_STGEN_MX = DATA_IO_DCS_BW_V_82;
    break;    
    default:
      OP_INTRFC_STGEN_MX = 0;
    break;
  }

  OP_INTRFC_MAN_STG_EN = OP_INTRFC_STGEN_MX;

//// MANUAL STAGE VALVE 1 BLOQUE 2

  switch (CNTRL_MODE_SELECT_I_NAME){
    
    case 2:
      OP_INTRFC_STG1_MX = DATA_IO_LL2_BW_V_83;
    break;
    case 3:
      OP_INTRFC_STG1_MX = DATA_IO_RL2_BW_V_83;
    break;    
    case 5:
      OP_INTRFC_STG1_MX = DATA_IO_DCS_BW_V_83;
    break;    
    default:
      OP_INTRFC_STG1_MX = 0;
    break;
  }

  OP_INTRFC_MAN_STG_01 = OP_INTRFC_STG1_MX;

